### ISSUE TITLE
openid-connect client create gives 500 error

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak-admin-ui#392]
When you create a openid-connect client with the wizard and set the switches both to on on the second page you get a 500 error:

![image](https://user-images.githubusercontent.com/51133/108811195-1c542280-75ad-11eb-8abc-8ffa3cac220f.png)

in the server log:

```
07:57:53,724 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-133) Uncaught server error: java.lang.RuntimeException: Client does not have a service account.
	at org.keycloak.keycloak-services@12.0.1//org.keycloak.authorization.admin.ResourceServerService.create(ResourceServerService.java:83)
	at org.keycloak.keycloak-services@12.0.1//org.keycloak.authorization.admin.AuthorizationService.enable(AuthorizationService.java:60)
	at org.keycloak.keycloak-services@12.0.1//org.keycloak.services.resources.admin.ClientsResource.createClient(ClientsResource.java:194)
```

**Comment by edewit** [comment]
with the new defaults the error changed a bit:

```
10:58:09,462 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-81) Uncaught server error: java.lang.RuntimeException: Only confidential clients are allowed to set authorization settings
```
