### ISSUE TITLE
Comment out localization tab

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#862]
Explanation is in https://github.com/keycloak/keycloak-admin-ui/pull/861

**Comment by ssilvert** [comment]
I need to record my thoughts and findings thus far as I need to stop working on it and come back later.

There is definitely a bug on the server side.  A NullPointerException, by definition, always indicates a bug.  However, this error only occurs when:
- Using the new admin console in development mode.
- On a realm other than master.
- Make a call on the localization REST API such as `admin/realms/mynewrealm/localization/en`
- (We think) Running on Keycloak 14+

This is the server-side code that fails:
`if (!AdminPermissions.realms(session, auth.adminAuth()).isAdmin()) {
            throw new ForbiddenException();
        }`

Specifically, the NPE happens on the call to `AdminPermissions.realms()`

What the code is doing is just making sure that the caller has permission to execute the API.  While almost all the REST endpoints have some kind of authorization check, I don't see any of the other REST endpoints doing it in quite the same way.

The nested exception is:
`Caused by: java.lang.NullPointerException
        at org.keycloak.keycloak-services@15.0.0-SNAPSHOT//org.keycloak.authorization.common.KeycloakIdentity.getUserFromToken(KeycloakIdentity.java:291)
        at org.keycloak.keycloak-services@15.0.0-SNAPSHOT//org.keycloak.authorization.common.KeycloakIdentity.<init>(KeycloakIdentity.java:232)
        ... 82 more`

So it looks like it is having a problem reading the token when we are in dev mode, but it all works fine if the new admin console is running as a Keycloak theme.

Since our Cypress tests run in dev mode, this is causing our tests to fail for every PR.
